export const GAZETTE_STORIES: string[] = [
  'The ship Tulloch Castle lies short-handed in Port Gannet harbour, her whole crew having deserted for the diggings; her master offers full pardon and full wages to any man who returns to his post before the tide.',
  "A miner's pan sold this week at Bell's Outfitters for the extraordinary sum of sixteen pounds, a record even by the standards of this field.",
  'Traffic on the road came to a complete standstill where the Razorback Road leaves Mercer\'s Track, dozens of drays and thousands of miners jammed together deciding which route to take, elegant gentlemen on fine-boned horses mixed in among kilted Scotsmen and runaway sailors still in their sea-garb.',
  'Twenty-two lives were lost to typhoid this season at a camp whose name we withhold out of respect for the bereaved; a government inspector had called its sanitation the worst in the colony not three months before.',
  'Two miners descending their shaft with a parcel of blasting powder on the platform beside them met with the inevitable result when a dropped candle found the fuse; one was killed outright, the other pulled alive from the wreck of the windlass.',
  'A dog, having got hold of a fish-bomb intended for a nearby waterhole, dragged its burning fuse directly through camp and very nearly relieved the Lucky Dish Shanty of its custom permanently.',
  'The Lucky Dish Shanty, a public house built of mud bricks scraped from a nearby creek bed, has been quietly and entirely dismantled by Chinese fossickers who correctly suspected the bricks themselves carried a colour of gold.',
  'A woman known to all as Mother Reilly pushed a wheelbarrow four days from Port Gannet to reach the diggings, her whole stock — a washing-tub of grog bottles — sold out within the hour of her arrival.',
  'Two candle-lighters caught red-handed at Copperhead Gully were tarred, feathered and run out of camp before the nearest trooper had so much as finished his breakfast.',
  'A gathering of bushflies over a stretcher led one sharp-eyed digger to a trickle of blood, a bloodstained axe, and a murderer who did not live to see a magistrate.',
  'A party of diggers pushed handcarts some four hundred miles from Port Gannet into the desert country rather than pay for a wagon, and every one of them arrived, if considerably thinner than they left.',
  'Ten men stood waist-deep in water for several hours freeing two drays whose axle-trees had broken in the mud at a nearby street; all ten have sworn to rot in gaol before paying another shilling toward the licence.',
  'Two doctors from Parramatta arrived on the field with a portable hospital complete with fifty coffins, every one packed to the lid with flour; the flour sold at twice its cost, and the empty coffins, it is said, will not want for custom either.',
  'A camp "doctor", a butcher by every trade but the one he now practises, stitched a digger\'s gashed arm with a hair from a horse\'s tail, there being nothing else to hand, and the patient is reported to be mending.',
  'The Bank of Australasia reports a record week of gold weighed and bought, most of it, by the manager\'s own account, spent again within the hour at the Crown & Cradle.',
  "A Cobb & Co. coach was very nearly bailed up on the Razorback Road last week; the driver's Bowie knife and the sight of his wild beard are credited with persuading the bushrangers toward easier custom elsewhere.",
  'A claim-jumping dispute at Blackcap Ranges ended without bloodshed only because both parties discovered, on drawing pistols, that neither man had thought to load his own.',
  'Lin Wu\'s garden outside Slateford has produced its finest cabbage crop of the season, much to the relief of a camp that has seen more than its share of scurvy this winter.',
  'The gold escort departed Slateford under heavy guard on Tuesday last, three strongboxes bound for the Bank of Australasia at Port Gannet and, from there, for London.',
  'A digger who ran four miles on nothing more than a rumoured strike arrived to find another party\'s stakes already driven and initialled; he is said to be philosophical about the whole affair, in language unfit for these pages.',
  'A puddling-machine owner at Copperhead Gully has been asked, politely but firmly, to allow claim-holders to watch their own dirt being worked, following certain unexplained discrepancies in the yield.',
  'A tent fire at the canvas town outside Port Gannet claimed six dwellings before it was brought under control; among the losses was, by report, a very fine collection of quart pots.',
  'The magistrate\'s monthly visit to Slateford saw eleven men fined for mining without a licence and two more sentenced to the chain gang for want of the money to pay.',
  'A brumby belonging to a Blackcap Ranges digger was observed scratching water from a dry creek bed that its owner had sworn, not an hour before, held none at all.',
  'Word reaches us of a rich reef struck at a camp its finders decline to name, though half of Slateford appears to have worked out the general direction by supper time.',
  'A new chum, three days off the boat, offered a storekeeper a genuine nugget in payment for a shilling\'s worth of tobacco and was, we are pleased to report, given honest change.',
  'The Council chambers report a marked increase in applications for claims since the last rich showing at Copperhead Gully, and an equally marked shortage of clerks to process them.',
  'A digger hunt at Reedbank Camp yielded eight arrests and, by several accounts, considerably more diggers hiding down their own shafts than troopers thought to check.',
  'A horse-coper operating near the Crown & Cradle has been selling showy hacks to new chums at prices that would embarrass a Port Gannet importer; buyers are advised to know a brumby from a parade horse before parting with their money.',
  'The Times regrets to report the loss of a cradle and its owner\'s entire week\'s washdirt to a flash flood on Slate River, the water having risen without warning in the space of a quarter hour.',
  'A quarrel over the division of gold between two former mates ended, as such quarrels too often do on this field, in a rope and a crowd that did not trouble to wait for a magistrate.',
  'Sunday work by Chinese miners at a claim near Slateford has drawn the usual complaints from neighbouring diggers, though the complainants were observed resting comfortably at the time.',
];

export const GAZETTE_ADS: string[] = [
  'GUTTA PERCHA SOLES — waterproof, cheaper and more durable than leather, fitted by any man without a shoemaker\'s skill. Ask for them wherever mining goods are sold.',
  'STEPHENS\' BLISTERING OINTMENT — for sunburn, saddle-sores and the general wear of the road. No digger\'s swag is complete without a tin.',
  "EAST INDIA PICKLES, finest quality, now landed at Bell's Outfitters. A relish for the plainest damper.",
  'PEEK FREAN\'S BISCUITS, imported direct, keep sound for months in a dry swag. Ask your storekeeper.',
  'LAVER & CO.\'S CORDIAL, a wholesome refreshment for the digger who has sworn off stronger stuff, at least for this week.',
  "PORT GANNET HOUSE, PRINTERS AND PUBLISHERS, Main Street, opposite the Bullock's Rest — publishers of The New Chum's Companion, price sixpence, and all manner of forms, licences and handbills promptly printed.",
  'COBB & CO. coaches depart Port Gannet thrice weekly for Slateford. Fares payable in advance; gold not accepted in lieu of coin.',
  "BELL'S FREIGHT carries goods and parcels to all outlying camps at reasonable rates. Enquire at Bell's Outfitters, Bell Street, Slateford.",
  'GOOD SOUND HORSES, brumbies a speciality, bought and sold on fair terms. No showy hacks foisted on the unwary. Apply near the Crown & Cradle.',
  'A PORTABLE HOSPITAL, complete with a dozen folded tents and twenty-five collapsible stretchers, for sale entire or in lots. Apply Canvas House.',
  'GUTTA PERCHA WASHING BOWLS, drinking mugs, flasks and tubing — every article the goldfields require, warranted watertight. Port Gannet House.',
  "WANTED: sober bullockies for the Port Gannet to Slateford run. Apply Bell's Outfitters, wages good, character required.",
  'MOLESKINS, cabbage-tree hats and cradles of every size supplied wholesale and retail. Prices lowest at Port Gannet; do not wait until the diggings.',
  'SIMPSON AND BELL\'S BISCUITS, a wholesome standby for the digger\'s swag, now stocked alongside Peek Frean\'s at all principal stores.',
  'THE BANK OF AUSTRALASIA, Slateford, buys gold at the fairest rate on the diggings. Weights checked in full view of the customer.',
  'LOST: one grey mare, brumby stock, answering to no name in particular. Reward offered, no questions asked.',
  "VENICE TURPENTINE, linseed oil, and every article for lamp and paint, now landed and for sale at Bell's Outfitters.",
  'TO LET: stable lodging, five shillings the night, clean straw guaranteed. Enquire at the yard behind the Crown & Cradle.',
];

export const CAMP_TALK: string[] = [
  'They say a digger at Blackcap Ranges ate a ten-pound note in a mutton sandwich rather than let the taxman have it.',
  'A man over at Copperhead Gully lit his cigar off a fiver, just to show he could.',
  'Heard tell of a fellow with a horseshoe made of solid gold, though I\'ll believe it when I see the horse limp under the weight of it.',
  'My tent\'s called Buckingham Palace now. The one next to it calls itself Windsor Castle, if you can credit the cheek of it.',
  'There\'s a chap three claims over swears he found a nugget shaped exactly like a boot.',
  'Word is the reef out past Reedbank Camp runs solid gold for a hundred feet, though nobody\'s ever actually seen it.',
  'A woman paid for her dinner in gold dust last week and the innkeeper near wept with joy.',
  'They\'re calling it the House of Lords now, that shanty by the crossing. Don\'t ask me why.',
  'Someone reckoned they saw the ghost of a digger down an old shaft at Copperhead Gully. I reckon they saw the bottom of a bottle instead.',
  'I heard a new chum offered a shopkeeper a real nugget for a plug of tobacco and got honest change back. First time for everything.',
  'A fossicker down by the mullock heaps turned up a nugget the size of a hen\'s egg not a week after the ground was declared worked out.',
  "There's talk of Widow's Reef out past the ranges, though every man who claims to know the way tells a different story.",
  'They say the licence fee\'s going up again. Half this camp\'s ready to rot in gaol first, or so they claim over their third rum.',
  'A bushranger held up a Cobb & Co. coach and found nothing in the strongbox but blankets and horse oats. Serves him right.',
  'Heard the puddling-machine owner\'s been light-fingered with more than one man\'s dirt this month.',
  'They\'re saying the Chinese found gold in the mud bricks of the old Lucky Dish Shanty. Pulled the whole place down brick by brick, I hear.',
  'A trooper took a fiver off my mate last week and never even wrote his name down.',
  'Someone struck it rich down at the river bend and won\'t say where, exactly, which tells you everything you need to know.',
  'The grog-seller\'s tent has burned down three times this year and she just puts up a new one and carries on.',
  'A digger at Slateford swears he saw a man pay for his supper with a solid gold coin he\'d cast himself. I\'d want to see that assayed first.',
  'There\'s a rumour going round that the reef at Blackcap Ranges is played right out, though the company\'s not saying so publicly.',
  'They found a man\'s boots and nothing else out past the Razorback Road. Bushrangers, or worse, nobody\'s in a hurry to say.',
];

/**
 * The licence question, as the Times reports it through 1854 (§20). The tiers
 * run from grumbling to open defiance; the paper picks by how hot the field is.
 */
export const AGITATION_STORIES: string[][] = [
  [
    'THE LICENCE. A correspondent asks by what right a man earning nothing is charged thirty shillings a month for the privilege of earning it. We print the letter without comment, our own opinion being well enough known.',
    'THE LICENCE. A deputation of diggers waited upon the Commissioner this week to ask that the fee be levied upon gold won rather than upon holes dug. They were heard with great courtesy and sent away with nothing.',
    'THE DIGGINGS. Talk at every camp fire is of the fee. A shilling a day, the diggers observe, when a labourer in the town earns five shillings the week and pays nothing at all for the right to earn it.',
    'THE LICENCE. We set down the arithmetic and leave it there. Thirty shillings the month is one shilling the day, or eighteen pounds the year, when a labourer\'s wage is five shillings a week and a shepherd receives a miserable ten pounds a year for his. The fee is not a tax upon gold; it is a tax upon hoping for it.',
  ],
  [
    'THE LICENCE. Another hunt at the camps this week, and two men taken who had paid their thirty shillings but left the paper in the tent. The Commissioner is reminded that the diggings are not a gaol yard.',
    'MEETINGS. Diggers met by torchlight on the flat on Tuesday, some hundreds of them, and passed resolutions against the fee with a show of hands that would have carried any parish in England.',
    'THE LICENCE. It is stated that the troopers were jeered from one end of the gully to the other, and that a sergeant\'s horse was turned loose for him to walk home after.',
  ],
  [
    'THE LICENCE. Licences were burned publicly at two camps this week, the papers held up on a shovel and fired to loud cheering. We do not commend the act; we observe merely that men are past reasoning with.',
    'AGITATION. A monster meeting is spoken of. Speakers demand the abolition of the fee, the vote, and the unlocking of the lands, and are heard by thousands standing in the sun without a hat among them.',
    'THE COMMISSIONER. His Honour\'s men were driven off the Gully flat on Thursday with clods and language, and did not return that day. The camp is now openly ungovernable on the licence question.',
  ],
  [
    'THE LICENCE. The field is past bearing. Diggers drill on the flat of an evening with pick-handles for muskets, and there is talk, not idle talk, of a stockade and a flag of their own.',
    'THE DIGGINGS. Storekeepers are laying in powder and shot, and the troopers no longer ride out in twos. Whatever is coming is coming quickly, and the Government has had a year\'s warning of it.',
    'AGITATION. Men who came out to dig gold now speak of rights, and of Ireland, and of what was done at Peterloo. A Government that would not remit thirty shillings may find it has bought something dearer.',
  ],
];
